export const siteRows = [
  {
    siteKey: 'stingerclean_main',
    domain: 'stingerclean.co.kr',
    owner: 'BOSS internal',
    language: 'ko',
    cluster: 'A',
    gLevel: 'G2',
    guardrail: 'HIGH',
    topic: 'HOME',
    portfolioStatus: 'operating_ready',
    approvalStatus: 'approved',
    riskLevel: 'low',
    monetizeMode: 'business',
    setupStatus: 'done',
    memo: '운영중인 청소 서비스 본진',
    wpBaseUrl: 'https://stingerclean.co.kr',
    credentialRef: 'STINGER_AUTH',
    workflow: 'A_PREMIUM',
    promptProfile: 'stinger_main_초안',
    model: 'hybrid / qwen2.5:32b',
    automationMode: 'DRAFT_ONLY',
    status: 'ACTIVE',
    adsense: 'approved',
    monthlyTarget: 12,
    reviewRequired: true,
  },
  {
    siteKey: 'sjournal_main',
    domain: 'sjournal.kr',
    owner: 'Customer owned',
    language: 'ko',
    cluster: 'G',
    gLevel: 'G2',
    guardrail: 'STANDARD',
    topic: 'MEDIA',
    portfolioStatus: 'operating_ready',
    approvalStatus: 'approved',
    riskLevel: 'low',
    monetizeMode: 'adsense_agency',
    setupStatus: 'done',
    memo: 'ESG 친환경 전문 매체',
    wpBaseUrl: 'https://sjournal.kr',
    credentialRef: 'SJOURNAL_AUTH',
    workflow: 'G_NEWS',
    promptProfile: 'sjournal_v1',
    model: 'CLAUDE',
    automationMode: 'DRAFT_ONLY',
    status: 'ACTIVE',
    adsense: 'approved',
    monthlyTarget: 20,
    reviewRequired: true,
  },
  {
    siteKey: 'emf_main',
    domain: 'emf-bioshield.com',
    owner: 'Customer owned',
    language: 'en',
    cluster: 'D',
    gLevel: 'G2',
    guardrail: 'YMYL',
    topic: 'LIFE',
    portfolioStatus: 'operating_ready',
    approvalStatus: 'approved',
    riskLevel: 'medium',
    monetizeMode: 'adsense',
    setupStatus: 'done',
    memo: '영문 건강 정보, YMYL 검수 필요',
    wpBaseUrl: 'https://emf-bioshield.com',
    credentialRef: 'EMF_AUTH',
    workflow: 'D_YMYL',
    promptProfile: 'emf_v1',
    model: 'CLAUDE',
    automationMode: 'DRAFT_ONLY',
    status: 'ACTIVE',
    adsense: 'approved',
    monthlyTarget: 8,
    reviewRequired: true,
  },
  {
    siteKey: 'achilles_main',
    domain: 'achillesmed.com',
    owner: 'Customer owned',
    language: 'en',
    cluster: 'D',
    gLevel: 'G2',
    guardrail: 'YMYL',
    topic: 'LIFE',
    portfolioStatus: 'recovery_review',
    approvalStatus: 'approved',
    riskLevel: 'high',
    monetizeMode: 'adsense',
    setupStatus: 'done',
    memo: 'WP-CLI 실패 이력 확인 필요',
    wpBaseUrl: 'https://achillesmed.com',
    credentialRef: 'ACHILLES_AUTH',
    workflow: 'D_YMYL',
    promptProfile: 'achilles_v1',
    model: 'CLAUDE',
    automationMode: 'DRAFT_ONLY',
    status: 'ACTIVE',
    adsense: 'approved',
    monthlyTarget: 8,
    reviewRequired: true,
  },
];

export const contentQueueRows = [
  {
    id: 188,
    siteKey: 'housingnews_main',
    title: '아파트 인테리어 초보도 쉽게 사용하는 최신 건축자재 TOP 7',
    keyword: '아파트 인테리어 건축자재',
    category: '홈인테리어·건축자재',
    status: 'READY',
    publishMode: 'draft',
    h2Count: 0,
    contentLength: 0,
    priority: 80,
  },
  {
    id: 189,
    siteKey: 'sjournal_main',
    title: '풍력발전 현황과 국내외 확산 전망 분석',
    keyword: '풍력발전',
    category: '신재생에너지',
    status: 'PUBLISHED',
    publishMode: 'publish',
    h2Count: 5,
    contentLength: 2012,
    priority: 40,
  },
  {
    id: 190,
    siteKey: 'sjournal_main',
    title: 'ESG 공급망 관리와 기업 지속가능성 전략',
    keyword: 'ESG 공급망',
    category: 'ESG경영',
    status: 'PASS',
    publishMode: 'draft',
    h2Count: 5,
    contentLength: 2948,
    priority: 50,
  },
];

export const wpSetupRows = [
  {
    domain: 'sjournal.kr',
    language: 'ko',
    linuxUser: 'sjournal',
    siteName: '에스저널',
    concept: 'ESG & 친환경 전문 매체',
    theme: 'kadence',
    monetize: 'adsense_agency',
    approval: '합격',
    status: 'DONE',
  },
  {
    domain: 'emf-bioshield.com',
    language: 'en',
    linuxUser: 'emf',
    siteName: 'EMF Health Lab',
    concept: '전자파 & 건강 정보',
    theme: 'astra',
    monetize: 'adsense',
    approval: '합격',
    status: 'DONE',
  },
  {
    domain: 'a-creative.kr',
    language: 'ko',
    linuxUser: 'agency',
    siteName: '에이크리에이티브',
    concept: '정부지원금 & 창업 정보',
    theme: 'generatepress',
    monetize: 'adsense',
    approval: '합격',
    status: 'PROCESSING',
  },
  {
    domain: 'achillesmed.com',
    language: 'en',
    linuxUser: 'achillesmed',
    siteName: 'Achilles Health Research Institute',
    concept: '재활 & 건강 정보 블로그',
    theme: 'astra',
    monetize: 'adsense',
    approval: '합격',
    status: 'DONE',
  },
];

export const workflowRows = [
  {
    key: 'WF-A',
    name: 'HOME Premium Draft',
    type: 'A_PREMIUM',
    target: '청소·홈케어',
    status: 'ACTIVE',
    lastRun: '대기',
  },
  {
    key: 'WF-G',
    name: 'Media News Pipeline',
    type: 'G_NEWS',
    target: '뉴스·정보 매체',
    status: 'ACTIVE',
    lastRun: '2026-05-02 09:03',
  },
  {
    key: 'WF-D',
    name: 'YMYL Review Pipeline',
    type: 'D_YMYL',
    target: '건강·의료·재활',
    status: 'REVIEW_ONLY',
    lastRun: '대기',
  },
];

export const runLogRows = [
  {
    time: '2026-05-02 09:03',
    siteKey: 'sjournal_main',
    workflow: 'G_NEWS',
    status: 'SUCCESS',
    cost: '$0.08',
    seconds: 131,
    result: 'WordPress post created',
  },
  {
    time: '2026-05-08 03:23',
    siteKey: 'achilles_main',
    workflow: 'WP_SETUP',
    status: 'FAILED',
    cost: '$0.00',
    seconds: 24,
    result: 'WP-CLI credential check failed',
  },
  {
    time: '대기',
    siteKey: 'housingnews_main',
    workflow: 'A_PREMIUM',
    status: 'QUEUED',
    cost: '$0.00',
    seconds: 0,
    result: 'Ready for N8N webhook',
  },
];

export const portalSummary = {
  domain: 'wordfriends.co.kr',
  role: 'CUSTOMER_PORTAL',
  status: 'PLANNED',
  publicPurpose: '고객 모집, 고객 로그인, 정산 확인, 소개 보상 관리',
  safetyDefault: '수익/승인 보장 금지, 고객 소유 계정 원칙',
};

export const customerRows = [
  {
    code: 'CUST-001',
    name: '파일럿 고객 A',
    contractStatus: 'ACTIVE',
    sites: 2,
    adsenseStatus: 'APPROVED',
    settlementStatus: 'CONFIRMED',
  },
  {
    code: 'CUST-002',
    name: '베타 고객 B',
    contractStatus: 'LEAD',
    sites: 0,
    adsenseStatus: 'NOT_STARTED',
    settlementStatus: 'NONE',
  },
  {
    code: 'CUST-003',
    name: '소개 대기 고객 C',
    contractStatus: 'PENDING',
    sites: 1,
    adsenseStatus: 'SUBMITTED',
    settlementStatus: 'DRAFT',
  },
];

export const settlementRows = [
  {
    month: '2026-05',
    customer: 'CUST-001',
    grossRevenue: '고객 직접 수령',
    agencyFee: '운영대행료 산정',
    status: 'CONFIRMED',
  },
  {
    month: '2026-05',
    customer: 'CUST-003',
    grossRevenue: '승인 대기',
    agencyFee: '미확정',
    status: 'DRAFT',
  },
];

export const referralRows = [
  {
    referrer: 'CUST-001',
    referred: 'CUST-003',
    depth: 1,
    rule: '1단계 소개 보상',
    active: true,
    status: 'PENDING',
  },
  {
    referrer: 'CUST-001',
    referred: 'CUST-004',
    depth: 2,
    rule: '2단계 확장 후보',
    active: false,
    status: 'DISABLED',
  },
];

export const taxEstimateRows = [
  {
    label: '소개 보상 예시',
    grossAmount: '100,000원',
    category: '사업소득 3.3% 참고',
    withholding: '3,300원',
    netPayable: '96,700원',
    status: 'REFERENCE',
  },
  {
    label: '기타소득 참고 예시',
    grossAmount: '100,000원',
    category: '기타소득 8.8% 참고',
    withholding: '8,800원',
    netPayable: '91,200원',
    status: 'REFERENCE',
  },
  {
    label: '사업자 정산',
    grossAmount: '세금계산서 기준',
    category: '세무 검토 필요',
    withholding: '별도 판단',
    netPayable: '별도 판단',
    status: 'REVIEW',
  },
];

export const notificationRows = [
  {
    id: 'notice-001',
    audience: 'customer',
    visibility: 'public_to_customer',
    title: '5월 예상 정산 리포트 업데이트',
    message: '고객 포털에서 이번 달 예상 정산금과 입금 예정일을 확인할 수 있습니다.',
    channel: 'portal',
    category: 'settlement',
    severity: 'info',
    status: 'ready',
    marketing: false,
  },
  {
    id: 'notice-002',
    audience: 'customer',
    visibility: 'public_to_customer',
    title: '계좌 및 세무 정보 확인 필요',
    message: '정산 전 고객 본인 명의 계좌와 세무 참고 정보를 확인해야 합니다.',
    channel: 'portal_sms',
    category: 'account_action',
    severity: 'action_required',
    status: 'draft',
    marketing: false,
  },
  {
    id: 'notice-003',
    audience: 'admin',
    visibility: 'internal_only',
    title: 'WordPress 연결 실패 반복',
    message: 'achillesmed.com WP 인증 실패가 반복되어 운영자 확인이 필요합니다.',
    channel: 'telegram',
    category: 'automation',
    severity: 'warning',
    status: 'ready',
    marketing: false,
  },
  {
    id: 'notice-004',
    audience: 'admin',
    visibility: 'internal_only',
    title: '도메인 만료 예정 확인',
    message: '만료 예정 도메인은 고객에게 공개하지 않고 내부에서 먼저 갱신 여부를 판단합니다.',
    channel: 'portal_telegram',
    category: 'domain',
    severity: 'critical',
    status: 'draft',
    marketing: false,
  },
];
